str = input('Enter a string of text:')
print('3rd symbol:', str[3])
print('Penultimate symbol:', str[-2])
print('First 5 symbols:', str[0:5])
print('All characters except last two:', str[:-2])
print('All even symbols:', str[1::2])
print('All odd symbols:', str[0::2])
print('Conversely :', str[::-1])
print('Conversely in 1 :', str[-1::-2])
print('Lenght of the line :', len(str))
